### ISSUE TITLE
FATAL error with some shell commands inside a network_dir

### ISSUE THREAD

**Issue by lakano** [nanobox-io/nanobox-docker-bridge#4]
Hi,

If you try to run « git add README.md » inside a network_dir, there is a permission denied error, caused in theory of a disk full or a wrong permissions.
The permissions are correctly set, owned by gonano user, the disk isn't full, and a « git init » works correctly ( folder .git created )

If you try without the network_dirs option, this works correctly. This seems to be a bug in the NFS options, surely something to tweak to prevent this.

Currently, our company can't uses nanobox to host our Git repositories. 

```
run.config:
    engine: nodejs
    extra_packages:
        - git

data.storage:
    image: nanobox/unfs:0.9

web.site:
    start: sleep 365d
    network_dirs:
        data.storage:
            - storage

```
Logs:
```
$ git add README.md 
fatal: error when closing sha1 file: Permission denied

```

Regards,
